services:
  db:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  location-ht:
    container_name: location-ht
    image: redis
    ports:
      - 6379:6379
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    volumes:
      - redis-data:/root/redis

volumes:
  db_data:
  redis-data: